#!/bin/bash

VIM="$HOME/.vimrc"
VIMDOT="$HOME/.dotfiles/.vimrc"
VIMBUN="$HOME/.vim/bundles"
BASH="$HOME/.bashrc"
BASHDOT="$HOME/.dotfiles/.bashrc"

#sets up vim
[ -L "$VIM" ] && unlink "$VIM" echo "unlinked old .vimrc"
[ -e "$VIM" ] && mv "$VIM" "$VIM.bak" && echo "Moved old .vimrc to "$VIM.bak""

ln -s "$VIMDOT" "$VIM"
echo "Created symbolic link for .vimrc"
mkdir -p "$VIMBUN"

vim -E -c PlugInstall -c q -c q
echo "Installed Plugins for Vim"

#sets up bash
[ -L "$BASH" ] && unlink "$BASH" echo "unlinked old .bashrc"
[ -e "$BASH" ] && mv "$BASH" "$BASH.bak" && echo "Moved old .bashrc to "$BASH.bak""

ln -s "$BASHDOT" "$BASH"
echo "Created symbolic link for .bashrc"

echo "DONE!"
