#!/bin/bash

#GitHub repo filepaths
ZSHDOT="$HOME/.dotfiles/zshrc.symlink"
VIMDOT="$HOME/.dotfiles/vimrc.symlink"
BASHDOT="$HOME/.dotfiles/bashrc.symlink"

#Local filepaths
VIM="$HOME/.vimrc"
VIMBUN="$HOME/.vim/bundles"
BASH="$HOME/.bashrc"
ZSH="$HOME/.zshrc"

#sets up vim
[ -L "$VIM" ] && unlink "$VIM" && echo "unlinked old .vimrc"
[ -e "$VIM" ] && mv "$VIM" "$VIM.bak" && echo "Moved old .vimrc to "$VIM.bak""

ln -s "$VIMDOT" "$VIM"
echo "Created symbolic link for .vimrc"
mkdir -p "$VIMBUN"

mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s ~/.vim $XDG_CONFIG_HOME/nvim
ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim

vim -E -c PlugInstall -c q -c q
echo "Installed Plugins for Vim"

#sets up bash
[ -L "$BASH" ] && unlink "$BASH" && echo "unlinked old .bashrc"
[ -e "$BASH" ] && mv "$BASH" "$BASH.bak" && echo "Moved old .bashrc to "$BASH.bak""

ln -s "$BASHDOT" "$BASH"
echo "Created symbolic link for .bashrc"

#sets up zsh
[ -L "$ZSH" ] && unlink "$ZSH" && echo "unlinked old .zshrc"
[ -e "$ZSH" ] && mv "$ZSH" "$ZSH.bak" && echo "Moved old .bashrc to "$ZSH.bak""

ln -s "$ZSHDOT" "$ZSH"

echo "Created symbolic link for .zshrc"

echo "DONE!"
