#!/usr/bin/env bash
set -e

msg() {
    printf "$(tput bold)%s$(tput sgr0)\n" "$*"
}

BASEDIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"
cd "${BASEDIR}"

# Fetch remote changes to see if there is a difference
git fetch --quiet

# Check for unstaged changes in the working directory
if ! git diff --quiet; then
    echo "WARNING: There are unstaged .dotfiles modifcations."

# Check if there are differences between local and remote
elif ! git diff --quiet HEAD origin/main; then
    msg 'WARNING: Local .dotfiles do not match latest commit.'
else
    echo ".dotfiles are up to date"
    exit 0
fi


msg 'Commit changes...'
git add -A
git diff --cached --exit-code &>/dev/null \
    || git commit

msg 'Pull remote changes...'
git pull

msg 'Update submodules...'
git submodule update --remote

msg 'Commit submodule changes...'
git add -A
git diff --cached --exit-code &>/dev/null \
    || git commit -m "Update remotes @ $(date -u -Is)"

msg 'Push local changes...'
git push

msg 'Install...'
./install
