#!/usr/bin/env bash
set -e

msg() {
    printf "$(tput bold)%s$(tput sgr0)\n" "$*"
}

get_commit_message() {
    read -r -p "Enter commit message (leave empty to cancel): " commit_msg
    echo "$commit_msg"
}

commit_changes() {
    msg "Commit changes..."
    git add -A
    if ! git diff --cached --quiet; then
        commit_msg=$(get_commit_message)
        if [ -n "$commit_msg" ]; then
            git commit -m "$commit_msg"
        else
            msg "Changes not committed."
            exit 1
        fi
    else
        msg "No changes to commit."
    fi
}

BASEDIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"
cd "${BASEDIR}"

# Fetch remote changes to see if there is a difference
git fetch --quiet

# Check for unstaged changes in the working directory
if ! git diff --quiet; then
    msg "There are unstaged .dotfiles modifications."
    commit_changes

# Check if there are staged but uncommitted changes
elif ! git diff --cached --quiet; then
    msg "There are staged .dotfiles modifications."
    commit_changes

# Check if there are differences between local and remote
elif ! git diff --quiet HEAD origin/main; then
    msg 'Local .dotfiles do not match latest commit.'
else
    msg ".dotfiles are up to date"
    exit 0
fi

msg 'Pull remote changes...'
git pull

msg 'Update submodules...'
git submodule init
git submodule update --remote

msg 'Commit submodule changes...'
commit_changes

msg 'Push local changes...'
git push

msg 'Install...'
./install
